import {
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CircleAlertIcon,
  CircleCheckIcon,
  CircleIcon,
  CircleXIcon,
  GripVerticalIcon,
  InfoIcon,
  MoonIcon,
  MoreHorizontalIcon,
  SearchIcon,
  SunIcon,
  XIcon,
} from 'lucide-react';

export const Icons = {
  Check: CheckIcon,
  ChevronDown: ChevronDownIcon,
  ChevronLeft: ChevronLeftIcon,
  ChevronRight: ChevronRightIcon,
  ChevronUp: ChevronUpIcon,
  Circle: CircleIcon,
  CircleAlert: CircleAlertIcon,
  CircleCheck: CircleCheckIcon,
  CircleX: CircleXIcon,
  GripVertical: GripVerticalIcon,
  Info: InfoIcon,
  Moon: MoonIcon,
  MoreHorizontal: MoreHorizontalIcon,
  Search: SearchIcon,
  Sun: SunIcon,
  X: XIcon,
};
